# docker role
- src: https://github.com/drBenway/ansible-docker
  name: docker

# intellij role
- src: https://github.com/drBenway/ansible-intellij
  name: intellij


# sublime role
- src: https://github.com/drBenway/ansible-sublime
  name: sublime

# visual studio role
- src: https://github.com/drBenway/ansible-vs
  name: vs
  

# wallpaper
- src: https://github.com/drBenway/ansible-wallpaper
  name: wallpaper
